[package]
name = "prqlr"
version = "0.10.0"
edition = "2021"
rust-version = "1.65"
publish = false

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
extendr-api = "0.6.0"
prql-compiler = { version = "0.10.0", default-features = false }
anstream = { version = "0.6.4", features = ["auto"] }
