[package]
name = "prqlr"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
# extendr-api = "0.3.1"
extendr-api = { git = "https://github.com/extendr/extendr", rev = "f511254b1be180528a1711e4c87473966a1010d0" }
# prql-compiler = { version = "0.4.2", default-features = false }
prql-compiler = { git = "https://github.com/PRQL/prql", rev = "58d4bccda5dd35c7579dd33ffef546d863b85c65", default-features = false }
anyhow = "1.0.68"
