[package]
name = "prqlr"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
extendr-api = "0.4.0"
prql-compiler = { version = "0.9.3", default-features = false }
anstream = { version = "0.3.2", features = ["auto"] }
