[package]
name = "prqlr"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
# extendr-api = "0.3.1"
extendr-api = { git = "https://github.com/extendr/extendr", rev = "974cddc4ee5a4c3ab10e8bf85772b74c0a182f32" }
# prql-compiler = { version = "0.4.2", default-features = false }
prql-compiler = { git = "https://github.com/PRQL/prql", rev = "764d8d089b931eaf0698983ae2266e2e91d52e2b", default-features = false }
anyhow = "1.0.68"
