[package]
name = "prqlr"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
# extendr-api = "0.3.1"
extendr-api = { git = "https://github.com/extendr/extendr", rev = "974cddc4ee5a4c3ab10e8bf85772b74c0a182f32" }
# prql-compiler = { version = "0.5.0", default-features = false }
prql-compiler = { git = "https://github.com/eitsupi/prql", rev = "bf7a49c9ee4d2c234c79a204623a4ecd111050c8", default-features = false }
anyhow = "1.0.68"
