[package]
name = "prqlr"
version = "0.11.0"
edition = "2021"
rust-version = "1.65"
publish = false

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
extendr-api = "0.6.0"
# prql-compiler = { version = "0.11.0", default-features = false }
# prql-compiler 0.11.0 is not compatible with Rust 1.65, so a slightly modified version is installed
# See https://github.com/PRQL/prql/pull/4001
prql-compiler = { git = "https://github.com/PRQL/prql", rev = "a1b73430ad433d335ef8695fbb4dc2ab657c6072", default-features = false }
anstream = { version = "0.3.2", features = ["auto"] }
