[package]
name = "prqlr"
version = "0.13.2"
edition = "2021"
rust-version = "1.73.0"
publish = false

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
savvy = "0.8"
prqlc= { version = "0.13.4", default-features = false }
