[package]
name = "prqlr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr" }
prql-compiler = { git = "https://github.com/prql/prql" }
