[package]
name = "prqlr"
version = "0.13.1"
edition = "2021"
rust-version = "1.81.0"
publish = false

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
savvy = "0.8"
prqlc= { version = "0.13.3", default-features = false }
