[package]
name = "prqlr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
# extendr-api = { git = "https://github.com/extendr/extendr" }
extendr-api = "0.3.1"
# prql-compiler = { git = "https://github.com/prql/prql" }
prql-compiler = "0.3.0"
anyhow = "1.0.66"
