[package]
name = "prqlr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['staticlib']
name = "prqlr"

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr", rev = "f511254b1be180528a1711e4c87473966a1010d0" }
# extendr-api = "0.3.1"
# prql-compiler = { git = "https://github.com/prql/prql" }
prql-compiler = { version = "0.4.0", default-features = false }
anyhow = "1.0.68"
strum = "0.24"
strum_macros = "0.24"
