# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_prqlr_wrappers", use_symbols = TRUE, package_name = "prqlr")

#' @docType package
#' @usage NULL
#' @useDynLib prqlr, .registration = TRUE
NULL

#' @title Compile a PRQL string into a SQL string
#' @param prql A PRQL string
#' @return A SQL string
#' @examples
#' "from mtcars | filter cyl > 6 | select [cyl, mpg]" |>
#'   prql_to_sql()
#'
#' "
#' from mtcars
#' filter cyl > 6
#' select [cyl, mpg]
#' " |>
#'   prql_to_sql() |>
#'   cat()
#' @export
prql_to_sql <- function(prql) .Call(wrap__prql_to_sql, prql)

#' @title Compile a PRQL string into a JSON version of the Query
#' @param prql A PRQL string
#' @return A JSON string of AST
#' @examples
#' "from mtcars | filter cyl > 6 | select [cyl, mpg]" |>
#'   prql_to_json() |>
#'   cat()
#' @seealso [json_to_prql()]
#' @export
prql_to_json <- function(prql) .Call(wrap__prql_to_json, prql)

#' @title Convert a JSON AST back to a PRQL string
#' @param json A JSON string of AST
#' @return A PRQL string
#' @seealso [prql_to_json()]
#' @examples
#' "from mtcars | filter cyl > 6 | select [cyl, mpg]" |>
#'   prql_to_json() |>
#'   json_to_prql() |>
#'   cat()
#' @export
json_to_prql <- function(json) .Call(wrap__json_to_prql, json)


# nolint end
