# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_prqlr_wrappers", use_symbols = TRUE, package_name = "prqlr")

#' @docType package
#' @usage NULL
#' @useDynLib prqlr, .registration = TRUE
NULL

#' @title Compile a PRQL string into a SQL string
#' @param query A PRQL string
#' @return A SQL string
#' @examples
#' "from mtcars \n filter cyl > 6 \n select [cyl, mpg]" |>
#'   prql_to_sql()
#' @export
prql_to_sql <- function(query) .Call(wrap__prql_to_sql, query)

