# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: pkgdown
on:
  push:
    branches:
      - main
    paths:
      - R/**
      - src/**
      - vignetts/**
      - _pkgdown.yml
      - DESCRIPTION
      - README.md
  pull_request:
    branches:
      - main
    paths:
      - R/**
      - src/**
      - vignetts/**
      - _pkgdown.yml
      - DESCRIPTION
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          Ncpus: "2"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        shell: Rscript {0}
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          clean: false
          branch: gh-pages
          folder: docs
